### ISSUE TITLE
issue with some themes

### ISSUE THREAD

**Issue by pcouchet** [Daniel-KM/Omeka-S-module-BlocksDisposition#1]
Hello Daniel,

The Block Disposition function runs perfectly with the "Default" and "Papers" Theme, not with "Center Row". 
The display of Map and Mirador is then no more controled by the Block Disposition Module.

What can I modify on "Center Row" ?

**Comment by Daniel-KM** [comment]
Bonjour Pierre,

Le module utilise l'événement `$this->trigger('view.show.before')` pour afficher ou non les blocs durant `$this->trigger('view.show.after')` et de même pour `browse`. Les deux événements doivent donc être présents dans les phtml.
Il faut donc ajouter les événemetns manquants et en profiter pour faire un pr sur le thème.
